name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-22.04, Ubuntu-20.04, macOS-12, macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Recompile Makefile
        run: make
      - name: Build Zipfile 
        run: make dist
      - name: Execute Tests
        run: make test

